### ISSUE TITLE
Requested feature: Temperature Conversions K<->C, K<->F, F<->C

### ISSUE THREAD

**Issue by NorthDecoder** [Tacoma-JS/weatherapp#6]
- See issue #5 for some algorithm hints.
- If a number is passed to the method the calculated result must be a number returned from the method. (Not output to console or HTML DOM).
  - If no number is passed to the method then return not a number 'NaN'.
- For clarity name the object that does the conversions 'convert', rather than 'wa'.
- Make the 'wa' object the wrapping object for all the other weather app objects
- Add the 'convert' object to the 'wa' object.
  - For example the usage would look like:

``` javascript
 var fahrenheit = wa.convert.KtoF(kelvin);
```
## Reference
- http://www.nist.gov/pml/wmd/metric/temp.cfm

**Comment by Avarayne** [comment]
This has been completed. 
Referenced https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature
for temperature conversion formulas. Merged into develop branch.
Commit # 465bed2

**Comment by NorthDecoder** [comment]
With Commit # [e0a2c46](https://github.com/Tacoma-JS/weatherapp/commit/e0a2c469d4b31d55a2674f833ff7bf9066c3f9a9#diff-e0f34b2e19d2a133f855a95559a644f1) I fixed the errors that I introduced while merging other features.

**Comment by NorthDecoder** [comment]
@Avarayne I will close this issue as complete, however there is a new issue #7 to address my observations and as an example I have changed  one of the tests in branch 'feature-test' file 'test.js' commit [8762c98](https://github.com/Tacoma-JS/weatherapp/commit/8762c98c4d87d2fd27cac06dd804394b45bf1f73) to show what I think the calculations should return.

For my edification on the same branch I did a calculation comparison in a new folder [docs](https://github.com/Tacoma-JS/weatherapp/blob/feature-tests/docs/temp_calc_comparisons.md)
